tlsconfig:
  truststore.pwd: "![UfBybbFP9yrcmUz7M+Lpnw==]"

inboundtls:
  key-password: "![UfBybbFP9yrcmUz7M+Lpnw==]"
  password: "![UfBybbFP9yrcmUz7M+Lpnw==]"

ntlmauthentication:
  username: "![VUZGd+9O1jYyDjRtqwPv4A==]"
  password: "![sT0mbNR3AkGQkJYABy9Z0x2+rqSV1kfXgsXF2WsNn24=]"

http:
  proxyUsername: "![VUZGd+9O1jYyDjRtqwPv4A==]"
  proxyPassword: "![sT0mbNR3AkGQkJYABy9Z0x2+rqSV1kfXgsXF2WsNn24=]"
